# Generated by Django 5.0.6 on 2024-06-02 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hotel', '0002_alter_hotel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('roomNumber', models.IntegerField()),
                ('roomType', models.CharField(max_length=100)),
                ('children', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('price', models.FloatField()),
                ('roomDescription', models.CharField(max_length=350)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('featureId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('featureName', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Features', to='Room.room')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facilityId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('facilityName', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Facilities', to='Room.room')),
            ],
        ),
        migrations.CreateModel(
            name='Roomimage',
            fields=[
                ('imageID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='media/rooms_images')),
                ('roomImagedesc', models.TextField(max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Roomimages', to='Room.room')),
            ],
        ),
    ]
