# Generated by Django 5.0.6 on 2024-06-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_alter_hotel_unique_together'),
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('roomNumber', 'roomType', 'hotel')},
        ),
    ]
