# Generated by Django 5.0.6 on 2024-06-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('facilityName', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('featureName', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='roomimage',
            unique_together={('image', 'room')},
        ),
    ]
