# Generated by Django 5.0.6 on 2024-06-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_items',
        ),
    ]
