# Generated by Django 5.0.6 on 2024-06-02 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotelID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('hotelDescription', models.CharField(max_length=350)),
                ('hotelEmail', models.EmailField(max_length=100, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_types', to='Hotel.hotelcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Hotelimage',
            fields=[
                ('imageID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='media/hotels_images')),
                ('hotelImagedesc', models.TextField(max_length=200)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hotelimages', to='Hotel.hotel')),
            ],
        ),
    ]
