# Generated by Django 5.0.6 on 2024-06-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together={('name', 'type', 'location')},
        ),
    ]
