# Generated by Django 5.0.6 on 2024-06-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_alter_hotel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotelimage',
            unique_together={('image', 'hotel')},
        ),
    ]
