# Generated by Django 5.0.6 on 2024-06-03 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_alter_hotelimage_unique_together'),
        ('Room', '0003_alter_facility_unique_together_and_more'),
        ('Roombooking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roombooking',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='roombooking',
            constraint=models.UniqueConstraint(fields=('hotel', 'room', 'checkinDate', 'checkoutDate'), name='unique_booking_per_period'),
        ),
    ]
